### ISSUE TITLE
Adding model includes returns incorrect paging count

### ISSUE THREAD

**Issue by Ryanthegiantlion** [feathersjs/feathers-sequelize#161]
When including associations from a one to many or many to many relationship, the total returned from find() is the size of the total result set. The count should be count of the primary model instances - no duplicates included.

Will add a test for this behaviour shortly.

**Comment by daffl** [comment]
Fixed via #162 in v2.3.1

**Comment by smaillns** [comment]
still have a similar issue with Pageable ! 
![image](https://user-images.githubusercontent.com/25650563/119629223-b7a3a080-be05-11eb-8067-15782a3a73f5.png)

**Comment by marknightingale** [comment]
@smaillns are you using a composite primary key?

The `select count()` that sequelize generates appears to take the first column that is defined as a primary key rather than using a `select count(*)`
